# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Binary release (linux,win)

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install pkg
      run: npm install -g pkg
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install root dependencies
      run: npm ci
    - name: Transpile to CommonJS
      run: gulp
    - name: Install binary distribution dependencies
      working-directory: ./dist
      run: npm ci
    - name: Build distribution binaries
      working-directory: ./dist
      run: pkg -d -C Gzip -t node16-linux-x64,node16-win-x64 .
    # - run: npm test
    - name: Release distribution binaries
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: |
          dist/frodo-linux
          dist/frodo-win.exe

