name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frodo
      uses: actions/checkout@v2
      with:
        path: frodo

    - name: Checkout frodolibs
      uses: actions/checkout@v2
      with:
        repository: rockcarver/frodolibs
        path: frodolibs

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        cd frodo
        go build -v ./...

    - name: Test
      run: |
        frodo
        go test -v ./...
